version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: company
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3309:3306"


  fastapi_app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: company
    depends_on:
      - db

# volumes:
#   db_data:
